### PR TITLE
SerialGC changes

### PR DESCRIPTION
**Pull request by fletchjp**
Allow for  different serial ports. These changes allow MEGA and DUE compiles to use Serial1, Serial2 or Serial3 instead of Serial.

### CODE REVIEW

**Comment by SvenRosvall** [comment]
Added David E as reviewer.
Added David H and Martin for information.

**Comment by david284** [comment]
Checked out the changes, and confirmed for myself that it compiles with the example (quite pleased I can run the arduino IDE on my chromebook - albeit a bit slow)
But I can't confirm it actually works, as I don't have any kit with me
So if you can confirm it does run, I'll be happy to approve the pull request

**Comment by SvenRosvall** [comment]
David E. Tried it out. Compiles and runs without any problems.

**Review by SvenRosvall — APPROVED** [review]

**Comment by MartinDaCosta53** [comment]
If you guys think it's OK, I have nothing to add.

**Review by david284 — APPROVED** [review]
Compiles ok for me

**Pull request merged**
