### PR TITLE
Refactorings to reduce code size

### PR DESCRIPTION
**Pull request by SvenRosvall**
Two refactorings that reduce code size a little.
* Change types from builtin types to the enum types defined in vlcbdefs.hpp. Some of these types are smaller than the "int" used earlier.
* Handling mode command for setting heartbeat on/off deduplicated.

### CODE REVIEW

**Review by MartinDaCosta53 — APPROVED** [review]
This also brings more consistency to the code eg opcode is sometimes a byte and others an int!

**Review by MartinDaCosta53 — COMMENTED** [review]
I haven't seen the syntax in the new line 501 before.  Is this an implied if statement?

**Comment by SvenRosvall** [comment]
> I haven't seen the syntax in the new line 501 before. Is this an implied if statement?

It is just a boolean (logical) expression being assigned to noHeartbeat. Looking at it now, I think I should have made it clearer with some parenthesis:
`noHeartbeat = (requestedMode == MODE_HEARTBEAT_OFF);`

It works because of the precedense rules in C++. "==" is evaluated before "=".

This is just a trick to make the code work for both ON and OFF. You can call it "implied if statement" if you want. The C++ term is just "boolean expression", i.e. just an expression that yields a boolean value.

**Comment by MartinDaCosta53** [comment]
Yes, that makes it clear.  Just took a bit to get my head round it!

**Pull request merged**
