### PR TITLE
Updates to MODE command

### PR DESCRIPTION
**Pull request by SvenRosvall**
Changes after adding unit tests for handling the MODE op-code.
These changes match my understanding of the current MODE as described in the MODE proposal document.

### CODE REVIEW

**Review by MartinDaCosta53 — COMMENTED** [review]
I agree with changing the cases to use constants, but where are these defined?  I can only see 3 defined in configuration.h in the enum ModuleMode.  Should the complete list be in vlcbdefs.hpp?

**Review by MartinDaCosta53 — COMMENTED** [review]
Oh, OK. Found them in the configuration.h changes.  We need to add Learn On and Learn Off

**Review by MartinDaCosta53 — COMMENTED** [review]
Oh, OK. Found them in the configuration.h changes.  We need to add Learn On and Learn Off

**Review by MartinDaCosta53 — COMMENTED** [review]
Save for making the enum ModuleMode in configuration.h fully comprehensive, this all looks fine to me.

**Comment by SvenRosvall** [comment]
> I agree with changing the cases to use constants, but where are these defined? I can only see 3 defined in configuration.h in the enum ModuleMode. Should the complete list be in vlcbdefs.hpp?

Hmm, I added MODE_HEARTBEAT_ON/OFF to Configuration.h in this change. Is it not visible?
Yes, I think this list should be added to vldbdefs.hpp. I'll do that when the MODE proposal is accepted.

**Comment by SvenRosvall** [comment]
> Save for making the enum ModuleMode in configuration.h fully comprehensive, this all looks fine to me.

I only added the MODE parameters that were needed in MNS. When they are added to VLCBDEFS I'll add the whole list.

**Comment by MartinDaCosta53** [comment]
EventTeachingService uses Learn Mode on and off and I think that we should update that from using hex numbers at the same time.  Why not just put the whole lot in vlcbdefs now?

**Pull request merged**
