### PR TITLE
Code trimming

### PR DESCRIPTION
**Pull request by SvenRosvall**
Some small changes to reduce code size both in source code and compiled code.

### CODE REVIEW

**Review by MartinDaCosta53 — COMMENTED** [review]
I'm wondering if line 72 is required.  The only time heartbeat is looked at is by MNS in the begin() function.  So, setting heartbeat = beat is superfluous as it is never used.

**Review by MartinDaCosta53 — COMMENTED** [review]
Where do I find stdarg.h?  Does this subsume vlcbdefs.hpp?

**Comment by SvenRosvall** [comment]
> Where do I find stdarg.h? Does this subsume vlcbdefs.hpp?

<stdarg.h> is a standard header. It is included in the Arduino IDE. It is used for the function sendMessageWithNNandData() on line 296 in Controller.h where we have the "..." for "any number of parameters". the names va_xxx are defined in stdarg.h and are used to handle those extra parameters. Let me know if you want an explanation how that works.

I took out vldbdefs.hpp here as it is already included by other header files.

These changes are not related.

**Comment by SvenRosvall** [comment]
> I'm wondering if line 72 is required in Configuration.ccp. The only time heartbeat is looked at is by MNS in the begin() function. So, setting heartbeat = beat is superfluous as it is never used. Same goes for line 87 eventAck = ea

Yes, looks like that can be reworked. There is a noHeartbeat in MNS. I guess the begin() function can look at the flag bit in module_config. Will look into this. But need your advice as you are the one who created this code.

**Comment by MartinDaCosta53** [comment]
I'll take it out and test it.  I'm pretty convinced that they're superfluous

**Comment by MartinDaCosta53** [comment]
> > I'm wondering if line 72 is required in Configuration.ccp. The only time heartbeat is looked at is by MNS in the begin() function. So, setting heartbeat = beat is superfluous as it is never used. Same goes for line 87 eventAck = ea
> 
> Yes, looks like that can be reworked. There is a noHeartbeat in MNS. I guess the begin() function can look at the flag bit in module_config. Will look into this. But need your advice as you are the one who created this code.

I'll take it out and test it. I'm pretty convinced that they're superfluous

**Comment by MartinDaCosta53** [comment]
> > Where do I find stdarg.h? Does this subsume vlcbdefs.hpp?
> 
> <stdarg.h> is a standard header. It is included in the Arduino IDE. It is used for the function sendMessageWithNNandData() on line 296 in Controller.h where we have the "..." for "any number of parameters". the names va_xxx are defined in stdarg.h and are used to handle those extra parameters. Let me know if you want an explanation how that works.
> 
> I took out vldbdefs.hpp here as it is already included by other header files.
> 
> These changes are not related.

That's rather clever.  I'd not heard of this before.

**Pull request merged**
