### PR TITLE
Update MinimumNodeService.cpp

### PR DESCRIPTION
**Pull request by MartinDaCosta53**
To align MNS with spec changes.

### CODE REVIEW

**Comment by SvenRosvall** [comment]
I wonder if we shall also change the 6 seconds required for the push button to change mode to 4 seconds?
Otherwise looks good.

**Comment by MartinDaCosta53** [comment]
Yes, we should.  Can I add a change to LEDUserInterface.h to this PR or should I merge and open another?

**Comment by MartinDaCosta53** [comment]
OK, added the time change.

**Comment by MartinDaCosta53** [comment]
All done

**Pull request merged**
